### ISSUE TITLE
Would you like to provide the Landmarks-clean datatset?

### ISSUE THREAD

**Issue by willard-yuan** [almazan/deep-image-retrieval#1]
@almazan Hi, Almazan,

I'm very interested in the series of deep image retrieval work. I have tried to reimplement the work of deep image retrieval, and download the Landmarks dataset from the [link](http://sites.skoltech.ru/compvision/projects/neuralcodes/), but some of the image links have been broken, and I was failed to reimplement since I have no Landmarks-clean last year. Would you like to provide the Landmarks-clean datatset? I want to train it on the Landmarks-clean again, So I could know the MAP performance on the public image retrieval dataset? Looking forward to your reply. Thanks.

**Comment by cesarsouza** [comment]
Hi @willard-yuan,

You can find the link for our annotations for the cleaned version of the landmarks dataset here: 

- http://download.europe.naverlabs.com/Computer-Vision-CodeandModels/

Unfortunately, we cannot provide the images themselves since we do not own the copyright for them. The best way to obtain the images for the cleaned version of Landmarks would have been to a) check with the authors of the original Landmarks dataset if they could provide you a copy of the image files, or b) attempt to download as many images as possible using their download script. After that, you can then use our provided annotations instead of theirs. 

You can also find more information (and other links) about our methods in this page:

https://europe.naverlabs.com/research/computer-vision/learning-visual-representations/deep-image-retrieval/


Hope it helps! 
Cesar

**Comment by willard-yuan** [comment]
@cesarsouza Thanks a lot for providing these useful information. Would you share the Landmarks-clean datatset for me? I just use it for academic research of CBIR.

I have test b) last year, but I found many links to download the images have broken. a) seems the last choice for me, and I'll try to contact with the authors of the original Landmarks dataset.

Thanks a lot.

**Comment by davidz123** [comment]
@willard-yuan Hello，I am trying on reimplement of this work. But l got problems when downloading datas with given url(can not reach the links). 
Did you got the data?   Will you share it?  
Thanks :)

**Comment by willard-yuan** [comment]
@davidz123 I haven't got the cleaned version of Landmarks. If you get the dataset, please share it with me. Thanks.
