### ISSUE TITLE
paper please?

### ISSUE THREAD

**Issue by JustinhoCHN** [almazan/deep-image-retrieval#7]
Hi Mr.Almazán,

Today I watched your video talk in deview 2018, you were giving a talk about "image retrieval with fashion aesthetics", I'm so interested about this method, but I searched for a while, I didn't find any paper name like this, can you provide the exact paper name or link you mentioned in the talk?

Best regards,
Justin

**Comment by almazan** [comment]
Hi Justin,

If you're referring to the attribute manipulation work, unfortunately there isn't a paper that describes that work. That talk is not about a publication but about an application for fashion retrieval that we built on top of our retrieval framework in order to showcase it at Deview.

However, the method used to build the common space between attributes and images is basically the method that is implemented in this repo and explained in [this paper](https://arxiv.org/abs/1610.07940): two 3-stream Siamese networks and a combination of triplet losses. So I believe that'd be the closest reference.

I hope that helps, and let me know if you have further questions.

**Comment by JustinhoCHN** [comment]
@almazan thank you, almazan.

You said it's a application built on top of your retrieval framework, is it a commercial application so that can not release more detail? If yes, totally understand.

Actually I've read your _Deep Image Retrieval_, the overall idea is roughly the same with _End-to-End Learning of Deep Visual Representations for Image Retrieval_ right?
The point that I'm interested in is that you composed the image feature and text feature with 2 stream triplet network, that idea is really attractive, but it seems that the paper you mentioned did't compose the text features?

I've studied fashion image retrieval for a while, I want to embed the fashion product attribute text info with image feature, to get a much more discriminative embedding, recentlly I read this paper: [_Composing Text and Image for Image Retrieval-An Empirical Odyssey_](http://openaccess.thecvf.com/content_CVPR_2019/papers/Vo_Composing_Text_and_Image_for_Image_Retrieval_-_an_Empirical_CVPR_2019_paper.pdf), the idea is similar with yours, the text feature is used to _modify_ the image feature, to get closer to those image with similar attribute. One of the  difference is the author using LSTM to model the text attribute, while you were using binary histogram.

I really want to try the method you mentioned in that talk, have you validated this method in any dataset? Or can you recommend me some good papers?

Forgive me so many quetions, thank you for your explanation.
